adding back logging
tracef and trace are gated by boolean - only 'costs' if
verbose_logging = true.

This isolated a problem with the proxy that sometimes causes the test to stall.

    2014-01-05T16:49:12.4409516Z: tests:run_with_factory -> listening
    2014-01-05T16:49:12.4429439Z: tests:run_with_factory <- listening
    2014-01-05T16:49:12.4450044Z: tests:req GET http://127.0.0.1:8084/ -> execute
    2014-01-05T16:49:12.4479361Z: tcp:tcp_ip_server - started listener: started 2014-01-05T16:49:12.4399538Z <-> 2014-01-05T16:49:12.4419493Z : 127.0.0.1:8084
    2014-01-05T16:49:12.4489548Z: web:request_loop:loop -> processor
    2014-01-05T16:49:12.4499485Z: web:request_loop:loop <- processor
    2014-01-05T16:49:12.4499485Z: web:request_loop:loop -> unblock
    2014-01-05T16:49:12.4579224Z: web:request_loop:loop -> processor
    2014-01-05T16:49:12.4589183Z: web:request_loop:loop <- processor
    2014-01-05T16:49:12.4589183Z: web:request_loop:loop -> unblock
    2014-01-05T16:49:12.4599071Z: web:request_loop:loop <- unblock
    2014-01-05T16:49:12.4609102Z: web:request_loop:loop -> flush
    2014-01-05T16:49:12.4609102Z: web:request_loop:loop <- flush
    2014-01-05T16:49:12.4658989Z: web:request_loop:loop <- unblock
    2014-01-05T16:49:12.4658989Z: web:request_loop:loop -> flush
    2014-01-05T16:49:12.4658989Z: web:request_loop:loop <- flush
    2014-01-05T16:49:12.4669291Z: web:request_loop:loop -> processor
    2014-01-05T16:49:17.4491609Z: web:request_loop:loop <- processor
    creating proxy/GET / returns 200 OK with passed string: Failed:
    GET / returns 200 OK with passed string-Falsifiable, after 1 test (0 shrinks) (StdGen (3544415,295809208)):
    ""
    with exception:
    Fuchu.AssertException: should finish request in 5000ms
    Expected: true
    Actual: false
       at <StartupCode$Fuchu>.$Assertions.Equal@8.Invoke(String msg) in g:\prg\Fuchu\Fuchu\Assertions.fs:line 8
       at Microsoft.FSharp.Core.PrintfImpl.go@523-3[b,c,d](String fmt, Int32 len, FSharpFunc`2 outputChar, FSharpFunc`2 outa, b os, FSharpFunc`2 finalize, FSharpList`1 a
    rgs, Int32 i)
       at Microsoft.FSharp.Core.PrintfImpl.run@521[b,c,d](FSharpFunc`2 initialize, String fmt, Int32 len, FSharpList`1 args)
       at Microsoft.FSharp.Core.PrintfImpl.capture@540[b,c,d](FSharpFunc`2 initialize, String fmt, Int32 len, FSharpList`1 args, Type ty, Int32 i)
       at <StartupCode$FSharp-Core>.$Reflect.Invoke@720-4.Invoke(T1 inp)
       at Fuchu.Assert.Equal[a](String msg, a expected, a actual) in g:\prg\Fuchu\Fuchu\Assertions.fs:line 8
       at Suave.Tests.RequestFactory.req_resp(Method methd, String resource, SuaveTestCtx ctx) in W:\_vendor\suave\Tests\Program.fs:line 77
       at Suave.Tests.proxy@148-5.Invoke(Unit unitVar0) in W:\_vendor\suave\Tests\Program.fs:line 148
       at Suave.Tests.RequestFactory.verbose_logging[a](FSharpFunc`2 f) in W:\_vendor\suave\Tests\Program.fs:line 43
       at Suave.Tests.proxy@146-4.Invoke(SuaveTestCtx _arg1) in W:\_vendor\suave\Tests\Program.fs:line 147
       at Suave.Tests.run_in_context@134-1.Invoke(FSharpFunc`2 f_body) in W:\_vendor\suave\Tests\Program.fs:line 135
       at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a)

      g:\prg\Fuchu\Fuchu.FsCheck\FsCheck.fs(23,1): Fuchu.FuchuFsCheckModule.runner@15.FsCheck-IRunner-OnFinished(String , TestResult )
     (00:00:05.0383362)
    9 tests run: 8 passed, 0 ignored, 1 failed, 0 errored (00:00:05.7789129)