fixing build prob
[18:58:30][Step 2/2] /opt/teamcity-agent/work/7bbf3ff0530572a9/Experimental/Template.fs(110,9): error FS0074: The type referenced through 'OpenSSL.X509.X509Certificate' is defined in an assembly that is not referenced. You must add a reference to assembly 'ManagedOpenSsl'.